// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwb6wO_6FSEx-1ZCsh7jZnDubwW5mM2tA',
    appId: '1:67323118123:web:68670a224538c9518f606e',
    messagingSenderId: '67323118123',
    projectId: 'agendamentotracker-7731d',
    authDomain: 'agendamentotracker-7731d.firebaseapp.com',
    storageBucket: 'agendamentotracker-7731d.firebasestorage.app',
    measurementId: 'G-CNLY0VFVL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWhxpkn4n9kWPdIJRK7DDJG_kCZZ8WJtc',
    appId: '1:67323118123:android:395b99caa7908c0b8f606e',
    messagingSenderId: '67323118123',
    projectId: 'agendamentotracker-7731d',
    storageBucket: 'agendamentotracker-7731d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdBszsQAvMrTK9JrGRF7vFYAQjnlI4F1k',
    appId: '1:67323118123:ios:8f1cc1b709d59b578f606e',
    messagingSenderId: '67323118123',
    projectId: 'agendamentotracker-7731d',
    storageBucket: 'agendamentotracker-7731d.firebasestorage.app',
    iosBundleId: 'com.example.rastreadorAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwb6wO_6FSEx-1ZCsh7jZnDubwW5mM2tA',
    appId: '1:67323118123:web:85b9e7ce0a383a138f606e',
    messagingSenderId: '67323118123',
    projectId: 'agendamentotracker-7731d',
    authDomain: 'agendamentotracker-7731d.firebaseapp.com',
    storageBucket: 'agendamentotracker-7731d.firebasestorage.app',
    measurementId: 'G-056ZLLMEQE',
  );
}
